# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml
image: node:16

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .nuxt/
    - docs/node_modules/
    - docs/.nuxt/

stages:
  - install
  - build
  - test

install-template-dependencies:
  stage: install
  script:
    - npm install

install-docs-dependencies:
  stage: install
  script:
    - cd docs
    - npm install

lint:
  stage: test
  script:
    - npm run lint

build-base:
  stage: build
  script:
    - npm run generate
  dependencies:
    - install-template-dependencies
  artifacts:
    paths:
      - dist/*

build-docs:
  stage: build
  script:
    - cd docs
    - npm run generate
  dependencies:
    - install-template-dependencies
    - install-docs-dependencies
  artifacts:
    paths:
      - docs/dist/*
